### PR TITLE
PrintStream not serializeable 😄

### LINKED ISSUE #23: Jenkins regression with 1.58 release
With 1.58, I see this in my logs:

```
7:59:36 ---
17:59:36 --- Jenkins Violation Comments to GitHub ---
17:59:36 ---
17:59:36 gitHubUrl: https://git.zias.io/api/v3
17:59:36 repositoryOwner: owl
17:59:36 repositoryName: owl-components
17:59:36 pullRequestId: 6
17:59:36 credentialsId: true
17:59:36 oAuth2Token: false
17:59:36 createSingleFileComments: true
17:59:36 createCommentWithAllSingleFileComments: false
17:59:36 commentOnlyChangedContent: false
17:59:36 minSeverity: WARN
17:59:36 keepOldComments: false
17:59:36 Checkstyle with pattern .*/checkstyle-result\.xml$
17:59:36 Findbugs with pattern .*/findbugsXml\.xml$
17:59:36 PMD with pattern .*/pmd\.xml$
17:59:36 Using OAuth2Token credential style
17:59:36 Running Jenkins Violation Comments To GitHub
17:59:36 PR 6
17:59:36 java.io.IOException: remote file operation failed: /var/lib/jenkins/workspace/owl_owl-components_PR-6-MWOBIXMJBAZPVGABQB72FSBTO2FM66EMCHCVZJY77BDNRFZZEHTQ at hudson.remoting.Channel@67ddca86:i-0280d5f9c00d288a8: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@54e8e2d2
17:59:36 	at hudson.FilePath.act(FilePath.java:993)
17:59:36 	at hudson.FilePath.act(FilePath.java:975)
17:59:36 	at org.jenkinsci.plugins.jvctg.perform.JvctgPerformer.jvctsPerform(JvctgPerformer.java:217)
17:59:36 	at org.jenkinsci.plugins.jvctg.ViolationsToGitHubRecorder.perform(ViolationsToGitHubRecorder.java:63)
17:59:36 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
17:59:36 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
17:59:36 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
17:59:36 	at hudson.security.ACL.impersonate(ACL.java:260)
17:59:36 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
17:59:36 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:59:36 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:59:36 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:59:36 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:59:36 	at java.lang.Thread.run(Thread.java:748)
17:59:36 Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@54e8e2d2
17:59:36 	at hudson.remoting.UserRequest.serialize(UserRequest.java:258)
17:59:36 	at hudson.remoting.UserRequest.<init>(UserRequest.java:99)
17:59:36 	at hudson.remoting.Channel.call(Channel.java:906)
17:59:36 	at hudson.FilePath.act(FilePath.java:986)
17:59:36 	... 13 more
17:59:36 Caused by: java.io.NotSerializableException: java.io.PrintStream
17:59:36 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
17:59:36 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
17:59:36 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
17:59:36 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
17:59:36 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
17:59:36 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
17:59:36 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
17:59:36 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
17:59:36 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
17:59:36 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
17:59:36 	at hudson.remoting.UserRequest._serialize(UserRequest.java:247)
17:59:36 	at hudson.remoting.UserRequest.serialize(UserRequest.java:256)
17:59:36 	... 16 more
17:59:36 
```

Same build with 1.57 plugin:

```
19:51:27 ---
19:51:27 --- Jenkins Violation Comments to GitHub ---
19:51:27 ---
19:51:27 gitHubUrl: https://git.zias.io/api/v3
19:51:27 repositoryOwner: owl
19:51:27 repositoryName: owl-components
19:51:27 pullRequestId: 6
19:51:27 usernamePasswordCredentialsId: true
19:51:27 useOAuth2TokenCredentials: false
19:51:27 oAuth2Token: false
19:51:27 createSingleFileComments: true
19:51:27 createCommentWithAllSingleFileComments: false
19:51:27 commentOnlyChangedContent: false
19:51:27 minSeverity: WARN
19:51:27 keepOldComments: false
19:51:27 Checkstyle with pattern .*/checkstyle-result\.xml$
19:51:27 Findbugs with pattern .*/findbugsXml\.xml$
19:51:27 PMD with pattern .*/pmd\.xml$
19:51:27 Running Jenkins Violation Comments To GitHub
19:51:27 PR 6
19:51:28 Workspace: /var/lib/jenkins/workspace/owl_owl-components_PR-6-MWOBIXMJBAZPVGABQB72FSBTO2FM66EMCHCVZJY77BDNRFZZEHTQ
19:51:28 Found 0 violations from ViolationConfig [pattern=.*/checkstyle-result\.xml$, reporter=Checkstyle, parser=CHECKSTYLE].
19:51:28 Found 0 violations from ViolationConfig [pattern=.*/findbugsXml\.xml$, reporter=Findbugs, parser=FINDBUGS].
19:51:28 Found 0 violations from ViolationConfig [pattern=.*/pmd\.xml$, reporter=PMD, parser=PMD].
19:51:28 Using username / password
19:51:28 PR: owl/owl-components/6 on https://git.zias.io/api/v3
```

Jenkins 2.89.2 (LTS, slightly behind), all other plugins fully upgraded. Building on a slave using Fleet plugin (EC2 spot instance).

### PR DESCRIPTION
**Pull request by casz**
fixes #23

### CODE REVIEW

**Comment by casz** [comment]
it might not be needed in logConfiguration :|

**Comment by tomasbjerre** [comment]
Yes, I tried it. We only need to change the logging in FIleCallable. I'll just make that change and keep the rest as is.

**Comment by casz** [comment]
@tomasbjerre sorry for not catching that :sad

**Comment by tomasbjerre** [comment]
No problem =)

**Pull request closed without merging**
