### PR TITLE
Combined credentials, Provide item context

### PR DESCRIPTION
**Pull request by casz**
like https://github.com/jenkinsci/violation-comments-to-stash-plugin/pull/50 but also deprecate the use of the token in clear text. Credential seems the superior option 👍

### CODE REVIEW

**Comment by tomasbjerre** [comment]
Wow, you did all three of them =) Nice!

**Comment by tomasbjerre** [comment]
Yes

**Comment by tomasbjerre** [comment]
This solves #19 right? Add #19 to any of the commits to make that issue appear in the changelog.

**Comment by casz** [comment]
@tomasbjerre should be good to review/go 👍

**Comment by tomasbjerre** [comment]
Great! I will review and test it as soon as possible.

**Comment by casz** [comment]
Sweet :kissing_heart:

**Comment by tomasbjerre** [comment]
Releasing now as 1.58. Thanks again @casz !

**Pull request merged**
